### ISSUE TITLE
Teb error

### ISSUE THREAD

**Issue by KatherineDuchesneau** [Y-Lammers/Split_on_Primer#4]
TabError: inconsistent use of tabs and spaces in indentation at the end of line 50.

**Comment by KatherineDuchesneau** [comment]
<img width="769" alt="screen shot 2018-06-05 at 13 16 49" src="https://user-images.githubusercontent.com/23107297/40991743-bf6d796c-68c2-11e8-8d94-cbedc5f602bd.png">

**Comment by wanglu2014** [comment]
replace empty with spaces
